<?php

namespace TweedeGolf\VideoBundle\Repository;

/**
 * VideoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Delete all existing videos,
     * should not be used carefully.
     */
    public function removeAll()
    {
        $query = $this->_em->createQuery('
            DELETE TGVideoBundle:Video v WHERE 1 = 1'
        );
        $query->execute();
    }
}
